name: Mod Build

on: workflow_dispatch

jobs:
  mod_build:
    permissions:
      contents: read
      packages: write
    uses: P3pp3rF1y/MultiWorkspace/.github/workflows/mod-build-template.yml@26.2
    secrets: inherit
